export function Dashboard() {
  return (
    <div className="space-y-6">
      <h1 className="text-2xl font-bold text-content-primary">Dashboard</h1>
      <p className="text-content-secondary">Dashboard content will be generated by vibe based on demo config.</p>
    </div>
  )
}
